//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FPL.Dal.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManuscriptSub
    {
        public int id { get; set; }
        public string ManuscriptNo { get; set; }
        public string Subject { get; set; }
        public string Title { get; set; }
        public string ManuscriptType { get; set; }
        public string Abstract { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string Plagiarismurl { get; set; }
        public string pdfurl { get; set; }
        public string docname { get; set; }
        public Nullable<int> TitleID { get; set; }
        public Nullable<int> ManuscriptTypeID { get; set; }
    }
}
