//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FPL.Dal.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Register_Table
    {
        public int RegisterID { get; set; }
        public string FullName { get; set; }
        public Nullable<int> Phone { get; set; }
        public string Email { get; set; }
        public string Profession { get; set; }
        public string Organisation { get; set; }
        public string College { get; set; }
        public string PostalAddress { get; set; }
        public string Area { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public Nullable<int> Pincode { get; set; }
        public string Password { get; set; }
        public string ConfirmPassword { get; set; }
        public string Captcha { get; set; }
        public Nullable<System.DateTime> CreratedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> RoleID { get; set; }
        public string RoleName { get; set; }
    }
}
